from typing import Protocol

from ..schemas import (
    User,
    Post,
    Comment,
)


class AuthRepository(Protocol):
    def register_user(self, email: str, hashed_pass: str) -> None: ...
    def get_user_credentials(self, email: str) -> tuple[int, str]: ...


class UserRepository(Protocol):
    def get(self, user_id: int) -> User: ...
    def save(self, user: User) -> User: ...
    def delete(self, user_id: int) -> User: ...


class PostRepository(Protocol):
    def all(self) -> list[Post]: ...
    def get(self, post_id: int) -> Post: ...
    def get_by_author(self, user_id: int) -> list[Post]: ...
    def save(self, post: Post) -> Post: ...
    def delete(self, post_id: int) -> Post: ...


class CommentRepository(Protocol):
    def get(self, comment_id: int) -> Comment: ...
    def get_by_author(self, user_id: int) -> list[Comment]: ...
    def get_by_post(self, post_id: int) -> list[Comment]: ...
    def save(self, comment: Comment) -> Comment: ...
    def delete(self, comment_id: int) -> Comment: ...
    def has_replies(self, comment_id: int) -> bool: ...